simulation:
  dimensions: [6, 6, 4]  # nx, ny, nz
  timestep: 1e-14        # dt in seconds
  steps: 10
  temperature: 11.0      # Kelvin
  mass: 12.0             # amu
  boundary_condition: 3   # 0=none, 1=periodic, 2=fixed, 3=lattice periodic
  track_particle: 1       # Particle ID to track
  write_output: true

potentials:
  lj:
    epsilon: 0.0026       # eV
    sigma: 3.440          # Å
    cutoff: 10.0          # Å
    smooth_ro: 8.0        # Å
    smooth_rc: 10.0       # Å
  morse:
    D_e: 6.0              # eV
    a: 2.0                # 1/Å
    r_e: 1.42             # Å
  cutoff_face: 0.1        # Å

lattice:
  basis_vectors:
    - [2.456, 0.0, 0.0]
    - [-1.228, 2.126958, 0.0]
    - [0.0, 0.0, 7.0]
  basis_atoms:
    - [0.0, 0.0, 0.25]
    - [0.0, 0.0, 0.75]
    - [1/3, 2/3, 0.25]
    - [2/3, 1/3, 0.75]

analysis:
  rdf:
    r_max: 40.0           # Å
    dr: 0.1               # Å
  heat_capacity:
    T_start: 1            # K
    T_end: 11             # K
    T_number: 5